export const KAFKA_MODULE_OPTIONS = Symbol("KAFKA_MODULE_OPTIONS");
export const KAFKA_PRODUCER_CLIENT = Symbol("KAFKA_PRODUCER_CLIENT");
export const KAFKA_CONSUMER_CLIENT = Symbol("KAFKA_CONSUMER_CLIENT");
export const SCHEMA_REGISTRY_CODEC = Symbol("SCHEMA_REGISTRY_CODEC");
export const KAFKA_INBOX_STORE = Symbol("KAFKA_INBOX_STORE");
